lotteries = [
    [
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 68, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 75, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 83, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 93, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 106, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 125, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 150, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 185, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 220, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 300, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 400, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 600, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 1000, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 10, "high_paym_B": 1700, "low_paym_B": 5},

        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 54, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 56, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 58, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 60, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 62, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 65, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 68, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 72, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 77, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 83, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 90, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 100, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 110, "low_paym_B": 5},
        {"high_paym_A": 40, "low_paym_A": 30, "high_paym_B": 130, "low_paym_B": 5},

        {"high_paym_A": 25, "low_paym_A": -4, "high_paym_B": 30, "low_paym_B": -21},
        {"high_paym_A": 4, "low_paym_A": -4, "high_paym_B": 30, "low_paym_B": -21},
        {"high_paym_A": 1, "low_paym_A": -4, "high_paym_B": 30, "low_paym_B": -21},
        {"high_paym_A": 1, "low_paym_A": -4, "high_paym_B": 30, "low_paym_B": -16},
        {"high_paym_A": 1, "low_paym_A": -8, "high_paym_B": 30, "low_paym_B": -16},
        {"high_paym_A": 1, "low_paym_A": -8, "high_paym_B": 30, "low_paym_B": -14},
        {"high_paym_A": 1, "low_paym_A": -8, "high_paym_B": 30, "low_paym_B": -11},
    ]
]
